//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ajustevonline.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;

    public partial class InspeccionesUlt
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InspeccionesUlt()
        {
            this.Images = new HashSet<Images>();
        }
    
        public int Id { get; set; }
        public int IdVehiculo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<Images> Images { get; set; }
        //[JsonIgnore]
        public virtual Vehiculos Vehiculos { get; set; }
    }
}
